# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: ABOUT
    url: /
    weight: 10
  - name: WRITING
    url: docs/
    weight: 20
  - name: BLOG
    url: blog/
    weight: 30
  - name: EVENTS
    url: showcase/
    weight: 40

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3
